const panData = [
        {
          pan: "AAAAA0000A",
          name: "Rahul",
          dob: "02-08-2003",
          fatherName: "Rajesh",
          address: "Mumbai",
        },
        {
          pan: "AAAAA0000B",
          name: "Rahul",
          dob: "09-09-1974",
          fatherName: "Rajesh",
          address: "Mumbai",
        },
        {
          pan: "AAAAA0000C",
          name: "Rahul",
          dob: "24-04-1996",
          fatherName: "Rajesh",
          address: "Mumbai",
        },
        {
          pan: "AAAAA0000D",
          name: "Rahul",
          dob: "13-05-2003",
          fatherName: "Rajesh",
          address: "Mumbai",
        },
        {
          pan: "AAAAA0000E",
          name: "Rahul",
          dob: "19-04-2001",
          fatherName: "Rajesh",
          address: "Mumbai",
        },
        {
          pan: "AAAAA0000F",
          name: "Rahul",
          dob: "22-05-1999",
          fatherName: "Rajesh",
          address: "Mumbai",
        },
        {
          pan: "AAAAA0000G",
          name: "Rahul",
          dob: "18-02-1986",
          fatherName: "Rajesh",
          address: "Mumbai",
        },
        {
          pan: "AAAAA0000H",
          name: "Rahul",
          dob: "02-10-1987",
          fatherName: "Rajesh",
          address: "Mumbai",
        },
        {
          pan: "AAAAA0000I",
          name: "Rahul",
          dob: "09-05-1984",
          fatherName: "Rajesh",
          address: "Mumbai",
        },
        {
          pan: "AAAAA0000J",
          name: "Rahul",
          dob: "10-07-2003",
          fatherName: "Rajesh",
          address: "Mumbai",
        },
        {
          pan: "AAAAA0000K",
          name: "Rahul",
          dob: "17-08-2000",
          fatherName: "Rajesh",
          address: "Mumbai",
        },
        {
          pan: "AAAAA0000L",
          name: "Rahul",
          dob: "24-02-2003",
          fatherName: "Rajesh",
          address: "Mumbai",
        },
        {
          pan: "AAAAA0000M",
          name: "Rahul",
          dob: "09-07-2003",
          fatherName: "Rajesh",
          address: "Mumbai",
        },
        {
          pan: "AAAAA0000N",
          name: "Rahul",
          dob: "05-00-2003",
          fatherName: "Rajesh",
          address: "Mumbai",
        },
        {
          pan: "AAAAA0000O",
          name: "Rahul",
          dob: "03-00-2003",
          fatherName: "Rajesh",
          address: "Mumbai",
        },
        {
          pan: "AAAAA0000P",
          name: "Rahul",
          dob: "12-05-2003",
          fatherName: "Rajesh",
          address: "Mumbai",
        },
        {
          pan: "AAAAA0000Q",
          name: "Rahul",
          dob: "02-02-2003",
          fatherName: "Rajesh",
          address: "Mumbai",
        },
        {
          pan: "AAAAA0000R",
          name: "Rahul",
          dob: "13-06-1974",
          fatherName: "Rajesh",
          address: "Mumbai",
        },
        {
          pan: "AAAAA0000S",
          name: "Rahul",
          dob: "03-07-1974",
          fatherName: "Rajesh",
          address: "Mumbai",
        },
        {
          pan: "AAAAA0000T",
          name: "Rahul",
          dob: "07-11-1992",
          fatherName: "Rajesh",
          address: "Mumbai",
        },
        {
          pan: "AAAAA0000U",
          name: "Rahul",
          dob: "02-09-1980",
          fatherName: "Rajesh",
          address: "Mumbai",
        },
        {
          pan: "AAAAA0000V",
          name: "Rahul",
          dob: "14-10-1978",
          fatherName: "Rajesh",
          address: "Mumbai",
        },
        {
          pan: "AAAAA0000W",
          name: "Rahul",
          dob: "08-09-2003",
          fatherName: "Rajesh",
          address: "Mumbai",
        },
        {
          pan: "AAAAA0000X",
          name: "Rahul",
          dob: "02-07-2003",
          fatherName: "Rajesh",
          address: "Mumbai",
        },
        {
          pan: "AAAAA0000Y",
          name: "Rahul",
          dob: "13-11-2003",
          fatherName: "Rajesh",
          address: "Mumbai",
        },
        {
          pan: "AAAAA0000Z",
          name: "Rahul",
          dob: "17-10-2003",
          fatherName: "Rajesh",
          address: "Mumbai",
        },
        {
          pan: "AAAAA0001A",
          name: "Rahul",
          dob: "21-09-1991",
          fatherName: "Rajesh",
          address: "Mumbai",
        },
        {
          pan: "AAAAA0001B",
          name: "Rahul",
          dob: "14-02-1988",
          fatherName: "Rajesh",
          address: "Mumbai",
        },
        {
          pan: "AAAAA0001C",
          name: "Rahul",
          dob: "27-10-1988",
          fatherName: "Rajesh",
          address: "Mumbai",
        },
        {
          pan: "AAAAA0001D",
          name: "Rahul",
          dob: "04-04-2003",
          fatherName: "Rajesh",
          address: "Mumbai",
        },
        {
          pan: "AAAAA0001E",
          name: "Rahul",
          dob: "22-02-1980",
          fatherName: "Rajesh",
          address: "Mumbai",
        },
        {
          pan: "AAAAA0001F",
          name: "Rahul",
          dob: "11-10-1974",
          fatherName: "Rajesh",
          address: "Mumbai",
        },
        {
          pan: "AAAAA0001G",
          name: "Rahul",
          dob: "02-06-2003",
          fatherName: "Rajesh",
          address: "Mumbai",
        },
        {
          pan: "AAAAA0001H",
          name: "Rahul",
          dob: "09-08-1975",
          fatherName: "Rajesh",
          address: "Mumbai",
        },
        {
          pan: "AAAAA0001I",
          name: "Rahul",
          dob: "10-04-1991",
          fatherName: "Rajesh",
          address: "Mumbai",
        },
        {
          pan: "AAAAA0001J",
          name: "Rahul",
          dob: "26-07-2003",
          fatherName: "Rajesh",
          address: "Mumbai",
        },
        {
          pan: "AAAAA0001K",
          name: "Rahul",
          dob: "05-02-1977",
          fatherName: "Rajesh",
          address: "Mumbai",
        },
        {
          pan: "AAAAA0001L",
          name: "Rahul",
          dob: "18-08-2003",
          fatherName: "Rajesh",
          address: "Mumbai",
        },
        {
          pan: "AAAAA0001M",
          name: "Rahul",
          dob: "03-07-1982",
          fatherName: "Rajesh",
          address: "Mumbai",
        },
        {
          pan: "AAAAA0001N",
          name: "Rahul",
          dob: "24-07-1987",
          fatherName: "Rajesh",
          address: "Mumbai",
        },
        {
          pan: "AAAAA0001O",
          name: "Rahul",
          dob: "16-04-2003",
          fatherName: "Rajesh",
          address: "Mumbai",
        },
        {
          pan: "AAAAA0001P",
          name: "Rahul",
          dob: "26-02-2003",
          fatherName: "Rajesh",
          address: "Mumbai",
        },
        {
          pan: "AAAAA0001Q",
          name: "Rahul",
          dob: "25-09-1977",
          fatherName: "Rajesh",
          address: "Mumbai",
        },
        {
          pan: "AAAAA0001R",
          name: "Rahul",
          dob: "03-03-2003",
          fatherName: "Rajesh",
          address: "Mumbai",
        },
        {
          pan: "AAAAA0001S",
          name: "Rahul",
          dob: "22-06-2003",
          fatherName: "Rajesh",
          address: "Mumbai",
        },
]


export default panData;